### ISSUE TITLE
/bug gives a bad credentials error when used

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#10744]

**Comment by silasary** [comment]
Github reset the token.

> We’re writing to let you know that we observed suspicious activity that suggests a threat actor used a Personal Access Token (PAT) associated with your account to access private repository metadata.
> Out of an abundance of caution, we reset your account password and revoked all of your Personal Access Tokens (classic), OAuth App tokens, and GitHub App tokens to protect your account, vorpal-buildbot.
