### ISSUE TITLE
"Forum Post" links on modobugs seem to all link to the "report a bug" page rather than a bug page

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#11428]

**Comment by bakert** [comment]
Example: https://github.com/PennyDreadfulMTG/modo-bugs/issues/1086

**Comment by silasary** [comment]
The "How to report" link is added by default so that it's easier for people to report and link forum posts.  They're *meant* to replace it with an actual link, but oftentimes they don't put the effort in.

Counterexample: https://github.com/PennyDreadfulMTG/modo-bugs/issues/1060

**Comment by bakert** [comment]
Oh I see. So this is wontfix?

**Comment by silasary** [comment]
Pretty much. I want to make the triage process better, but the issue as reported is "user error, wontfix"

**Comment by silasary** [comment]
Added [Needs Forum Post](https://github.com/PennyDreadfulMTG/modo-bugs/issues?q=is%3Aissue+is%3Aopen+label%3A%22Needs+Forum+Post%22) autolabel
