### ISSUE TITLE
Use legality[legacy] to determine if a card is "playable" or not, not layout

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#11630]
Scryfall recently added "Virtuous // Royal" (a token) as layout=flip breaking the previous clean division between "layouts that are playable" and "layouts that are not playable". This was what they suggested was the best way to determine if a card might be useful to us. Obviously we will have to check for banned as well as legal, but presumably tokens and things have some other value than legal/banned that mean we can ignore them.

**Comment by silasary** [comment]
Non-game pieces will have `legacy: "not_legal"`.  Note that this would exclude [Gleemox](https://scryfall.com/card/prm/26584/gleemox), a card that ostensibly has the potential to become PD Legal.

**Comment by bakert** [comment]
After much chat on the Scryfall discord we did this with:

```
-            if p.get('type_line') == 'Card':
+            # Exclude "Card"s which is a whole group of weird things, and also any tokens that have a playable layout.
+            if re.search(r'\b(token|card)\b', p.get('type_line', ''), re.IGNORECASE):
                 continue
```
