### ISSUE TITLE
During rotation (after run 136) Ashen Rider showed with rank "-" but was played a bunch this season

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#11674]
"-" means has been legal before but not played.

**Comment by bakert** [comment]
<img width="521" alt="image" src="https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/assets/1541/22f863bb-af95-4e5a-b594-1f9f8952e08b">

**Comment by bakert** [comment]
Also affects Sigarda, Host of Herons and other cards. It's cards that were legal for the first time this season. So we're not including the current season in Rank. We should.

**Comment by silasary** [comment]
I think it's more that the playability calculation is being run on the rotation machine, which doesn't have latest decks

**Comment by bakert** [comment]
Ah, yes, that's it. I wonder if we should rejig.

**Comment by bakert** [comment]
This is effectively a dupe of #11949
