### ISSUE TITLE
Hybrid phyrexian mana not displayed correctly by the bot

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#12028]
We probably need some new Discord emojis? Not sure if we have room.

<img width="710" alt="image" src="https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/assets/1541/2bcc5aba-c66a-4122-bdb0-436c0dce85b2">

**Comment by silasary** [comment]
The server is boosted, so we have plenty of room.

**Comment by bakert** [comment]
Sourced from https://github.com/scryfall/manamoji-discord/commit/07424d083f1617b65516a2cfcd466e4b9701a033 and added. We still have 30 more slots free. I cant' get the bot to use them yet, but we're getting there …

**Comment by bakert** [comment]
2b1c8a0
