### ISSUE TITLE
Wrong mtgo account name linked

### ISSUE THREAD

**Issue by cmartin112** [silasary/Penny-Dreadful-Discord-Bot#9581]
I am logged in to penny dreadful as cmartin and my mtgo name is cmartin112. PDbot does not recognize when I sign up for a league because of the difference. Is there a way to fix this?

**Comment by bakert** [comment]
I have disassociated both cmartin and cmartin112 from any Discord account.

I have merged cmartin into cmartin112 so that all decks appear under cmartin112 now.

You can re-associate your discord account with cmartin112 at https://pennydreadfulmagic.com/link/
