### ISSUE TITLE
Helper to find cheap deck

### ISSUE THREAD

**Issue by ghost** [silasary/Penny-Dreadful-Discord-Bot#9977]
It would be nice if I could import an mtgo collection in the pennydreadful website and get a list of the cheapest decks.

Right now I have 0.46 tix left on cardhoarder and I was trying to find a deck but all I can do is see the price of the complete deck. If I go deck by deck, eliminating the cards I already have, before checking the price for the rest of the cards in cardhoarder, is going to take me forever.

Also having the option of selecting to exclude the sideboard cards would be useful too.

**Comment by bakert** [comment]
Given the existence of the Cardhoarder Free Loan Program I think we're unlikely to support this.

If you don't know about it, it's a totally free way to loan cards up to a value of $5 – https://www.cardhoarder.com/free-loan-program-faq
